---
train:
  params:
    batch_size: 32
    epoch: 60
    lr: 0.00001
    decay: 0.1
    decay_step: 5000
    loss: MSELoss
  save:
    save_path: "./models"
    model_name: GazeNet
    step: 10
  data:
      image: "./MPIIGaze/Data/Original"
      label: "./MPIIGaze/Label"
  pretrains: "None"
test:
   load:
      begin_step: 60
      end_step: 60
      steps: 10
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Gaze-Net"
      model_name: GazeNet
   data:
      image: "./MPIIGaze/Data/Normalized"
      label: "./MPIIGaze/Label"
